name: meta2data
channels:
  - conda-forge
dependencies:
  - python=3.11
  - frictionless=5.18
  - pandas=2.2
  - pytest=7.3
  - jinja2=3.1
  - fire=0.7
  - python-dotenv=1
  - pip
  - pip:
    - 'tablecloth[excel,gsheets] @ git+https://github.com/ezwelty/tablecloth@e9e3431'
    - 'validator @ git+https://github.com/ezwelty/validator@507175e'
